"""empty message

Revision ID: 0d27ca423619
Revises: bd1c3b7416b1
Create Date: 2020-10-01 20:04:32.879807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d27ca423619'
down_revision = 'bd1c3b7416b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.drop_constraint('producto_ibfk_1', 'producto', type_='foreignkey')
    op.create_foreign_key(None, 'producto', 'categoria', ['categoria_id'], ['id'])
    op.drop_column('producto', 'id_categoria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.create_foreign_key('producto_ibfk_1', 'producto', 'categoria', ['id_categoria'], ['id'])
    op.drop_column('producto', 'categoria_id')
    # ### end Alembic commands ###
