"""empty message

Revision ID: 419f27fdd672
Revises: 37fd893c9cd3
Create Date: 2020-10-06 04:12:48.842439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419f27fdd672'
down_revision = '37fd893c9cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('icono', table_name='categoria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('icono', 'categoria', ['icono'], unique=True)
    # ### end Alembic commands ###
