"""empty message

Revision ID: e6fbbe871bf5
Revises: 0d27ca423619
Create Date: 2020-10-01 21:53:08.249888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fbbe871bf5'
down_revision = '0d27ca423619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('imagen', sa.String(length=150), nullable=True))
    op.add_column('producto', sa.Column('precio', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'precio')
    op.drop_column('producto', 'imagen')
    # ### end Alembic commands ###
